channels:
  - conda-forge
  - robostack
  - robostack-staging
  - pytorch
  - pytorch3d
  - nvidia
dependencies:
  - python==3.9.*
  - ros-noetic-desktop
  - ros-noetic-ros-numpy
  - catkin_tools
  - cmake
  - pybind11
  - pinocchio
  - pytorch==1.13.*  # Compatibility with pytorch3d
  - pytorch-cuda=11.7
  - pytorch3d
  - opencv
  - pip
  - pip:
    - numpy <1.24 # certain deprecated operations were used in other deps
    - scipy
    - sophuspy
    - pybullet
    - trimesh
    - pytest
    - open3d
    - scikit-image
    - scikit-fmm
    - scikit-learn
    - numpy-quaternion
    - natsort
    # Neural networks
    - openai-clip
    - timm
    - pandas
    - mss
    # visualizations and debugging
    - matplotlib
    # Command line tools
    - click
    # data tools
    - yacs
    - h5py
    - imageio
    - pygifsicle
    - pynput
