repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: |
            (?x)^(
                src/home_robot/home_robot/agent/perception/detection/lseg/|
                src/home_robot/home_robot/perception/detection/detic/
            )

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: |
            (?x)^(
                src/home_robot/home_robot/agent/perception/detection/lseg/|
                src/home_robot/home_robot/perception/detection/detic/
            )

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.981
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive, --no-strict-optional, --ignore-missing-imports]
        exclude: |
            (?x)^(
                src/home_robot/home_robot/agent/|
                src/home_robot/home_robot/utils/data_tools/|
                src/home_robot_hw/|
                src/home_robot/home_robot/agent/perception/detection/lseg/|
                src/home_robot/home_robot/perception/detection/detic/|
                projects/|
                src/home_robot/home_robot/experimental/
            )|setup.py$

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: |
            (?x)^(
                src/home_robot/home_robot/agent/|
                src/home_robot/home_robot/utils/|
                src/home_robot_hw/|
                src/home_robot/home_robot/agent/perception/detection/lseg/|
                src/home_robot/home_robot/perception/detection/detic/|
                projects/|
                src/home_robot/home_robot/experimental/|
                tests/
            )