name:
  slap_base
channels:
  - conda-forge
  - default
  - pytorch
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - cudatoolkit=11.6
  - torchvision=0.13.1
  - trimesh
  - h5py
  - imageio
  - pdbpp
  - mypy
  - pylint
  - pinocchio
  - cmake
  - pybind11
  - pip
  - pip:
    - numpy <1.24 # certain deprecated operations were used in other deps
    - scipy
    - sophuspy
    - opencv-python>=3.3.0
    - pybullet
    - trimesh
    - pytest
    - open3d
    - scikit-image
    - scikit-fmm
    - numpy-quaternion
    # Neural networks
    - openai-clip
    - timm
    # visualizations and debugging
    - matplotlib
    # Command line tools
    - click
    # data tools
    - yacs
    - pygifsicle
    - perceiver-pytorch
    - wandb
