channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - torchaudio
  - pytorch
  - cudatoolkit=11.6
  - torchvision
  - trimesh
  - h5py
  - imageio
  - opencv
  - seaborn
  - flake8
  - vulture
  - pyright
  - black
  - isort
  - ripgrep
  - pdbpp
  - neovim
  - mypy
  - pylint
  - json
  - pinocchio
  - cmake
  - pybind11
  - pip:
    - numpy <1.24 # certain deprecated operations were used in other deps
    - scipy
    - sophuspy
    - opencv-python>=3.3.0
    - pybullet
    - trimesh
    - pytest
    - open3d
    - scikit-image
    - scikit-fmm
    - numpy-quaternion
    # Neural networks
    - openai-clip
    - timm
    # visualizations and debugging
    - matplotlib
    # Command line tools
    - click
    # data tools
    - yacs
    - h5py
    - imageio
    - pygifsicle

