validate: False
datadir: "/home/priparashar/robopen_h5s/larp/kinesthetic_dataset/all_tasks/kin_data"
template: "*/*.h5"
load: False
resume: False
debug: False
learning_rate: 1e-3
task_name: all_tasks_viewpoint_dropout_jitter_DA
source: robopen
run_for: -1
wandb: False
split: "/home/priparashar/Development/slap_stretch/home-robot/projects/slap_manipulation/assets/task_splits/main_split.yaml"
data_augmentation: True
color_jitter: True
loss_fn: "xent"

