# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_rpc_env.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12task_rpc_env.proto\x12\x0ctask_rpc_env"g\n\x15\x41\x63tOnObservationsArgs\x12\x12\n\nepisode_id\x18\x01 \x01(\x05\x12,\n\x03obs\x18\x02 \x01(\x0b\x32\x1f.task_rpc_env.ProtoObservations\x12\x0c\n\x04goal\x18\x03 \x01(\t"*\n\x18\x41\x63tOnObservationsReturns\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t"\x11\n\x0fNextEpisodeArgs"{\n\x12NextEpisodeReturns\x12\x12\n\nepisode_id\x18\x01 \x01(\x05\x12\x0c\n\x04goal\x18\x02 \x01(\t\x12,\n\x03obs\x18\x03 \x01(\x0b\x32\x1f.task_rpc_env.ProtoObservations\x12\x15\n\rtask_complete\x18\x04 \x01(\x08".\n\x08StepArgs\x12\x12\n\nepisode_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t"w\n\x0bStepReturns\x12\x12\n\nepisode_id\x18\x01 \x01(\x05\x12,\n\x03obs\x18\x02 \x01(\x0b\x32\x1f.task_rpc_env.ProtoObservations\x12\x12\n\nsuccessful\x18\x03 \x01(\x08\x12\x12\n\nterminated\x18\x04 \x01(\x08"\xa2\x01\n\x11ProtoObservations\x12!\n\x19low_level_output_messages\x18\x01 \x03(\t\x12\x33\n\x0cscene_images\x18\x02 \x03(\x0b\x32\x1d.task_rpc_env.ProtoSceneImage\x12\x35\n\robject_images\x18\x03 \x03(\x0b\x32\x1e.task_rpc_env.ProtoObjectImage"0\n\x0fProtoSceneImage\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0e\n\x06values\x18\x02 \x03(\x02"j\n\x10ProtoObjectImage\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0e\n\x06values\x18\x02 \x03(\x02\x12\x10\n\x08position\x18\x03 \x03(\x02\x12\x0f\n\x07\x63rop_id\x18\x04 \x01(\x05\x12\x14\n\x0cobject_class\x18\x05 \x01(\t2\xe4\x01\n\tAgentgRPC\x12h\n\x17rpc_act_on_observations\x12#.task_rpc_env.ActOnObservationsArgs\x1a&.task_rpc_env.ActOnObservationsReturns"\x00\x12m\n\x1astream_act_on_observations\x12#.task_rpc_env.ActOnObservationsArgs\x1a&.task_rpc_env.ActOnObservationsReturns"\x00(\x01\x32\xa2\x01\n\x08TaskgRPC\x12U\n\x10rpc_next_episode\x12\x1d.task_rpc_env.NextEpisodeArgs\x1a .task_rpc_env.NextEpisodeReturns"\x00\x12?\n\x08rpc_step\x12\x16.task_rpc_env.StepArgs\x1a\x19.task_rpc_env.StepReturns"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "task_rpc_env_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:

    DESCRIPTOR._options = None
    _globals["_ACTONOBSERVATIONSARGS"]._serialized_start = 36
    _globals["_ACTONOBSERVATIONSARGS"]._serialized_end = 139
    _globals["_ACTONOBSERVATIONSRETURNS"]._serialized_start = 141
    _globals["_ACTONOBSERVATIONSRETURNS"]._serialized_end = 183
    _globals["_NEXTEPISODEARGS"]._serialized_start = 185
    _globals["_NEXTEPISODEARGS"]._serialized_end = 202
    _globals["_NEXTEPISODERETURNS"]._serialized_start = 204
    _globals["_NEXTEPISODERETURNS"]._serialized_end = 327
    _globals["_STEPARGS"]._serialized_start = 329
    _globals["_STEPARGS"]._serialized_end = 375
    _globals["_STEPRETURNS"]._serialized_start = 377
    _globals["_STEPRETURNS"]._serialized_end = 496
    _globals["_PROTOOBSERVATIONS"]._serialized_start = 499
    _globals["_PROTOOBSERVATIONS"]._serialized_end = 661
    _globals["_PROTOSCENEIMAGE"]._serialized_start = 663
    _globals["_PROTOSCENEIMAGE"]._serialized_end = 711
    _globals["_PROTOOBJECTIMAGE"]._serialized_start = 713
    _globals["_PROTOOBJECTIMAGE"]._serialized_end = 819
    _globals["_AGENTGRPC"]._serialized_start = 822
    _globals["_AGENTGRPC"]._serialized_end = 1050
    _globals["_TASKGRPC"]._serialized_start = 1053
    _globals["_TASKGRPC"]._serialized_end = 1215
# @@protoc_insertion_point(module_scope)
