defaults:
  - _self_
  - semantic_sensor: grounded_sam_perception
  - voxel_map: default

_target_: build_sparse_voxel_map.SparseVoxelMapAgent
device: 'cuda:0'
global_nms_thresh: 0.3
instance_box_compression_resolution: 0.01
instance_box_compression_drop_prop: 0.2
